### ISSUE TITLE
Running into issues running docker-compose up

### ISSUE THREAD

**Issue by aritraghosh** [LeoMcA/fitbit-grafana#3]
```
[7/8] RUN bundle install:
#0 0.494 /usr/local/bundle/gems/bundler-2.0.1/lib/bundler/shared_helpers.rb:272:in `search_up': undefined method `untaint' for "/myapp":String (NoMethodError)
#0 0.494 
#0 0.494       current  = File.expand_path(SharedHelpers.pwd).untaint
#0 0.494                                                     ^^^^^^^^
#0 0.494 	from /usr/local/bundle/gems/bundler-2.0.1/lib/bundler/shared_helpers.rb:259:in `find_file'
#0 0.494 	from /usr/local/bundle/gems/bundler-2.0.1/lib/bundler/shared_helpers.rb:251:in `find_gemfile'
#0 0.494 	from /usr/local/bundle/gems/bundler-2.0.1/lib/bundler/shared_helpers.rb:27:in `root'
#0 0.494 	from /usr/local/bundle/gems/bundler-2.0.1/lib/bundler.rb:234:in `root'
#0 0.494 	from /usr/local/bundle/gems/bundler-2.0.1/lib/bundler.rb:244:in `app_config_path'
#0 0.494 	from /usr/local/bundle/gems/bundler-2.0.1/lib/bundler.rb:273:in `settings'
#0 0.494 	from /usr/local/bundle/gems/bundler-2.0.1/lib/bundler/feature_flag.rb:21:in `block in settings_method'
#0 0.494 	from /usr/local/bundle/gems/bundler-2.0.1/lib/bundler/cli.rb:97:in `<class:CLI>'
#0 0.494 	from /usr/local/bundle/gems/bundler-2.0.1/lib/bundler/cli.rb:7:in `<module:Bundler>'
#0 0.494 	from /usr/local/bundle/gems/bundler-2.0.1/lib/bundler/cli.rb:6:in `<top (required)>'
#0 0.494 	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
#0 0.494 	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
#0 0.494 	from /usr/local/bundle/gems/bundler-2.0.1/exe/bundle:23:in `block in <top (required)>'
#0 0.494 	from /usr/local/bundle/gems/bundler-2.0.1/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
#0 0.494 	from /usr/local/bundle/gems/bundler-2.0.1/exe/bundle:22:in `<top (required)>'
#0 0.494 	from /usr/local/bundle/bin/bundle:25:in `load'
#0 0.494 	from /usr/local/bundle/bin/bundle:25:in `<main>'
------
failed to solve: executor failed running [/bin/sh -c bundle install]: exit code: 1

```

**Comment by aritraghosh** [comment]
Updating the bundler to 2.4.1 fixed it
